### ISSUE TITLE
Use datashim for helm with terraform

### ISSUE THREAD

**Issue by v1nc3nt27** [datashim-io/datashim#100]
Hi,

I'd like to integrate your awesome project into my terraform script, using helm. I'm kind of a beginner with helm, so I was wondering if you could explain to me how to add the datashim charts as a repo. As far as I understand, it requires an index.yaml which I cannot find in the charts. 
I could install it with kubectl and the yaml file, but I'd like to exclude the efs driver as I do not need it and I don't want it to waste resources.

If you intentionally didn't add an index.yaml, could you please point me into the right direction of how to handle this? Creating my own index.yaml? Thanks a lot in advance!

**Comment by YiannisGkoufas** [comment]
Hi @v1nc3nt27 ! thanks for your kind words! I wasn't aware for the `index.yaml` approach, wasn't done intentionally.
Will try to provide a helm repo soon. In the meantime I can guide you to achieve what you are looking for.
All the helm related resources are on https://github.com/datashim-io/datashim/blob/master/chart/
If you have a look on https://github.com/datashim-io/datashim/blob/master/Makefile#L3 basically we use helm to populate the uber-yaml file needed for installation. You can see the flags that we use in the command and you can invoke `helm install` instead of `helm template`. Now if you want to disable one or more of the charts you can do it the same way I do it for the `csi-h3-chart` in here: https://github.com/datashim-io/datashim/blob/master/Makefile#L9
By looking at the https://github.com/datashim-io/datashim/blob/master/chart/values.yaml file you can customize it as you want.
For instance for disabling nfs charts you need to add the option `--set csi-nfs-chart.enabled="false"` in your helm commands.
Hope that was helpful!

**Comment by v1nc3nt27** [comment]
Hey @YiannisGkoufas, sorry for the late reply, I must have missed the mail notification.

Thanks a lot for the instructions! I understand how it works a lot better now. So I basically clone the project and use `helm install` like you have done in your makefile. Sounds easy enough :). The only issue is that I will probably not be able to automate this with terraform (or at least not in a clean way), but it's much better than fiddling around with the yaml files.

Wrt to the index.yaml: It's probably a bit more complicated than just adding an index.yaml with some info (https://helm.sh/docs/topics/chart_repository/), but if I understand correctly this is the way if you want to enable installing from a URL directly like e.g. `helm install mynginx https://example.com/charts/nginx-1.2.3.tgz`. Might be a nice addition to the project :).

**Comment by srikumar003** [comment]
Closing this issue as it has been resolved
