### ISSUE TITLE
can't understand what the storage size means

### ISSUE THREAD

**Issue by zerr0s** [datashim-io/datashim#213]
Hello,

I'm making a test to mount a S3 bucket into my deployment (pods). When I have created the Dataset, a new PVC has been created with a size set to `5Gi`.

But inside the pod the volume seems to have much spaces:
`mymount  1.0P     0  1.0P   0% /mnt/s3`

I presume that this infromation provides from my cloud provider. So I'd like to know if it could be an issue if the pvc is set to 5gi ? How could I set the size using the dataset ?

Thanks for your help.

**Comment by srikumar003** [comment]
@zerr0s Since object storage has no defined limits on capacity (and is not a filesystem on a sized volume), `csi-s3` sets the storage size to an arbitrarily large number. Cloud providers do not provide the information about the maximum size of a bucket (since it can grow to any size)

What this means is that you can read/write to the dataset volume without worrying about running into size limits.

**Comment by zerr0s** [comment]
ok ok. thanks. So i will not wondeer abiut any size limit ;)

have a nice day.

**Comment by arezvani** [comment]
You can not get the information about the maximum size (limit) of a bucket if providers provide that?
